name: Publish to NuGet

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC trusted publishing
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Pack
        run: dotnet pack src/SqlInliner/SqlInliner.csproj -c Release --output ./nupkg

      - name: NuGet login (OIDC)
        uses: nuget/login@v1
        id: login
        with:
          user: ${{ vars.NUGET_USER }}

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
